library(tidyverse)

n <- 15000

ru_regions <- c(
  "RU-TOM",
  "RU-AD",
  "RU-KC",
  "RU-IN",
  "RU-KB",
  "RU-SE",
  "RU-STA",
  "RU-CHU",
  "RU-KGD",
  "RU-MUR",
  "RU-NGR",
  "RU-LEN",
  "RU-SPE",
  "RU-BRY",
  "RU-SMO",
  "RU-KR",
  "RU-ARK",
  "RU-IVA",
  "RU-KOS",
  "RU-NIZ",
  "RU-TVE",
  "RU-VLG",
  "RU-YAR",
  "RU-KLU",
  "RU-KRS",
  "RU-LIP",
  "RU-MOS",
  "RU-ORL",
  "RU-ROS",
  "RU-TUL",
  "RU-VGG",
  "RU-BEL",
  "RU-KDA",
  "RU-MO",
  "RU-PNZ",
  "RU-RYA",
  "RU-TAM",
  "RU-VLA",
  "RU-VOR",
  "RU-BA",
  "RU-CHE",
  "RU-KGN",
  "RU-NEN",
  "RU-YAN",
  "RU-KO",
  "RU-KIR",
  "RU-ME",
  "RU-SVE",
  "RU-UD",
  "RU-AST",
  "RU-CU",
  "RU-KL",
  "RU-ORE",
  "RU-SAM",
  "RU-SAR",
  "RU-TA",
  "RU-ULY",
  "RU-KHM",
  "RU-OMS",
  "RU-TYU",
  "RU-ALT",
  "RU-AL",
  "RU-KEM",
  "RU-KK",
  "RU-NVS",
  "RU-CE",
  "RU-DA",
  "RU-IRK",
  "RU-KYA",
  "RU-TY",
  "RU-BU",
  "RU-AMU",
  "RU-ZAB",
  "RU-PRI",
  "RU-SA",
  "RU-YEV",
  "RU-KHA",
  "RU-MAG",
  "RU-PER",
  "RU-KAM",
  "RU-PSK",
  "RU-SAK",
  "RU-MOW"
)

data <- tibble(age = sample(x = 17:70, size = n, replace = TRUE, prob = 70:17),
               cat0 = sample(x = c(0, 1), size = n, replace = TRUE, prob = c(0.8, 0.2)),
               cat1 = sample(x = c(0, 1), size = n, replace = TRUE, prob = c(0.7, 0.3)),
               cat2 = sample(x = c(0, 1), size = n, replace = TRUE, prob = c(0.9, 0.1)),
               cat3 = sample(x = c("a", "b", "c"), size = n, replace = TRUE, prob = c(0.6, 0.2, 0.2)),
               region_iso = sample(x = ru_regions, size = n, replace = TRUE))


data %>%
  ggplot(aes(x = age)) +
  geom_bar()

write_csv(x = data,
          file = file.path("..", "public", "data.csv"))
